[project]
name = "ios-backup-browser"
description = "Browser and exporter for iOS backups"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/greatvovan/ios-backup-browser"

[dependency-groups]
dev = [
    "pytest>=9.0.0",
]

[tool.setuptools_scm]
write_to = "ios_backup/_version.py"

[tool.pytest.ini_options]
pythonpath = ["src"]
